spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    #实例主机名
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/